INSERT INTO Ils VALUES ('Adana');
INSERT INTO Ils VALUES ('Adýyaman');
INSERT INTO Ils VALUES ('Afyonkarahisar');
INSERT INTO Ils VALUES ('Aðrý');
INSERT INTO Ils VALUES ('Amasya');
INSERT INTO Ils VALUES ('Ankara');
INSERT INTO Ils VALUES ('Antalya');
INSERT INTO Ils VALUES ('Artvin');
INSERT INTO Ils VALUES ('Aydýn');
INSERT INTO Ils VALUES ( 'Balýkesir');
INSERT INTO Ils VALUES ( 'BIlsecik');
INSERT INTO Ils VALUES ( 'Bingöl');
INSERT INTO Ils VALUES ( 'Bitlis');
INSERT INTO Ils VALUES ( 'Bolu');
INSERT INTO Ils VALUES ( 'Burdur');
INSERT INTO Ils VALUES ( 'Bursa');
INSERT INTO Ils VALUES ( 'Çanakkale');
INSERT INTO Ils VALUES ( 'Çankýrý');
INSERT INTO Ils VALUES ( 'Çorum');
INSERT INTO Ils VALUES ( 'Denizli');
INSERT INTO Ils VALUES ( 'Diyarbakýr');
INSERT INTO Ils VALUES ( 'Edirne');
INSERT INTO Ils VALUES ( 'Elazýð');
INSERT INTO Ils VALUES ( 'Erzincan');
INSERT INTO Ils VALUES ( 'Erzurum');
INSERT INTO Ils VALUES ( 'Eskiþehir');
INSERT INTO Ils VALUES ( 'Gaziantep');
INSERT INTO Ils VALUES ( 'Giresun');
INSERT INTO Ils VALUES ( 'Gümüþhane');
INSERT INTO Ils VALUES ( 'Hakkari');
INSERT INTO Ils VALUES ( 'Hatay');
INSERT INTO Ils VALUES ( 'Isparta');
INSERT INTO Ils VALUES ( 'Mersin(Ýçel)');
INSERT INTO Ils VALUES ( 'Ýstanbul');
INSERT INTO Ils VALUES ( 'Ýzmir');
INSERT INTO Ils VALUES ( 'Kars');
INSERT INTO Ils VALUES ( 'Kastamonu');
INSERT INTO Ils VALUES ( 'Kayseri');
INSERT INTO Ils VALUES ( 'Kýrklareli');
INSERT INTO Ils VALUES ( 'Kýrþehir');
INSERT INTO Ils VALUES ( 'Kocaeli');
INSERT INTO Ils VALUES ( 'Konya');
INSERT INTO Ils VALUES ( 'Kütahya');
INSERT INTO Ils VALUES ( 'Malatya');
INSERT INTO Ils VALUES ( 'Manisa');
INSERT INTO Ils VALUES ( 'Kahramanmaraþ');
INSERT INTO Ils VALUES ( 'Mardin');
INSERT INTO Ils VALUES ( 'Muðla');
INSERT INTO Ils VALUES ( 'Muþ');
INSERT INTO Ils VALUES ( 'Nevþehir');
INSERT INTO Ils VALUES ( 'Niðde');
INSERT INTO Ils VALUES ( 'Ordu');
INSERT INTO Ils VALUES ( 'Rize');
INSERT INTO Ils VALUES ( 'Sakarya');
INSERT INTO Ils VALUES ( 'Samsun');
INSERT INTO Ils VALUES ( 'Siirt');
INSERT INTO Ils VALUES ( 'Sinop');
INSERT INTO Ils VALUES ( 'Sivas');
INSERT INTO Ils VALUES ( 'Tekirdað');
INSERT INTO Ils VALUES ( 'Tokat');
INSERT INTO Ils VALUES ( 'Trabzon');
INSERT INTO Ils VALUES ( 'Tunceli');
INSERT INTO Ils VALUES ( 'Þanlýurfa');
INSERT INTO Ils VALUES ( 'Uþak');
INSERT INTO Ils VALUES ( 'Van');
INSERT INTO Ils VALUES ( 'Yozgat');
INSERT INTO Ils VALUES ( 'Zonguldak');
INSERT INTO Ils VALUES ( 'Aksaray');
INSERT INTO Ils VALUES ( 'Bayburt');
INSERT INTO Ils VALUES ( 'Karaman');
INSERT INTO Ils VALUES ( 'Kýrýkkale');
INSERT INTO Ils VALUES ( 'Batman');
INSERT INTO Ils VALUES ( 'Þýrnak');
INSERT INTO Ils VALUES ( 'Bartýn');
INSERT INTO Ils VALUES ( 'Ardahan');
INSERT INTO Ils VALUES ( 'Iðdýr');
INSERT INTO Ils VALUES ( 'Yalova');
INSERT INTO Ils VALUES ( 'Karabük');
INSERT INTO Ils VALUES ( 'KIlsis');
INSERT INTO Ils VALUES ( 'Osmaniye');
INSERT INTO Ils VALUES ( 'Düzce');